### ISSUE TITLE
How can I get TakeHorizontalScrollingScreenshot working

### ISSUE THREAD

**Issue by Lakritzator** [mwinapi/mwinapi#5]
I have made a small project to play around with mwinapi, especially for the scrolling capture.
It would be nice to have such a feature in Greenshot.

But somehow I can't get it working....

I do get a screenshot, and I do see a single "scroll" action on the window I used to test it on.
Before I start debugging like a maniac, maybe you can give me some hints?

I used Notepad++ with some text in it, found the window, than found the child with the text, made sure the window is active (actually I didn't find a call for this in SystemWindow??) moved the mouse inside the text area, called the TakeHorizontalScrollingScreenshot with the following call:
Screenshot.TakeHorizontalScrollingScreenshot(scrollPoint, child, null)

P.S.
Will write contact you via email about some contributions to this repository I might want to make.
As a Greenshot developer I have a lot of similar code, which is not nice to have double...
(recently moved this code to https://github.com/dapplo/Dapplo.Windows)

**Comment by schierlm** [comment]
Two hints:

1) Give it some time. I have seen that analyzing the screen takes 30 seconds or so. Probably the algorithm can be optimized quite a lot (pull requests welcome!), it was always "good enough for my needs"

2) The project https://github.com/mwinapi/mwinapi/tree/master/Tools/ScreenShooter uses all the features in the Screenshot class (a binary of it is also available in the ManagedWinapiTools package on SourceForge in case you do not want to compile it yourself), and can be used both as a reference how to use it, as well as testing whether this class is able to scan the window. I tested it with Notepad++ quickly, and it worked. [On the other hand, if I needed a "screenshot" of some Notepad++ window, I'd use Notepad++ "Export as HTML" plugin which is faster and creates HTML instead of an image.]

I will separately reply to the email you sent me.
