### ISSUE TITLE
SystemListViewItem title

### ISSUE THREAD

**Issue by tasoss** [mwinapi/mwinapi#7]
Hello and thanks for mwinapi!
I'm having the following problem.
I'm trying to get the column values from a SystemListView.
Although i can correctly get the width etc the Title is always empty.
Moreover the SystemListViewItem  rows are displayed correctly(dynamically adding/deleting some of them)
appear correct via the api.
Thanks!

**Comment by donid** [comment]
It has been quite a long time since I have worked with SystemListView, but if I remember it correctly, when I encountered that problem, I assumed that the window I was "spying on" used some kind of "owner draw". Have you tried to get the column values from a windows Explorer in "details view" or from a 7-Zip (main-)window? I have just tried those with [this tool](http://www.softwareok.com/?seite=Microsoft/GetWindowText) and they worked fine.  So, you can compare the output of this tool to the results you are getting from the API to see if there is a problem with the API or if the column values are really empty.

**Comment by tasoss** [comment]
Hello and thx for replying.Well i don't know if this is by design but after  compiling the project for x64 it started working as expected.I can now get the Title value.....I suppose it has to do with mem allocation not considering the arch?I don't know just guessing.
Thanks again!
